#!/bin/bash

ztosec () {
  h=$(echo $1 | cut -c -2)  # 00
  m=$(echo $1 | cut -c 4-5)  # 01
  s=$(echo $1 | cut -c 7-) # 49.68
  offset=.10
  echo $(echo "$h*60*60+$m*60+$s+$offset" | bc)
}

zcapture () {
  rm -r ~/.wine/drive_c/wa/User/Capture
  export WINEDEBUG=fixme-all
  wine 'C:\WA\WA.exe' /getvideo "$(winepath -w replays/$0.WAgame)" 1 $1 $1 800 640
  capdir="/home/boggy/.wine/drive_c/wa/User/Capture/$0"
  until [ -d "${capdir}" ]; do sleep .2; echo 'slept'; done
  mkdir -p "data/dynamite/$0"
  for f in "$capdir"/*; do
    for i in $(seq 0 20); do
      if [ ! -f "data/dynamite/$0/$i.png" ]; then
        mv "$f" "data/dynamite/$0/$i.png"
        echo "game $0 num $i"
        break
      fi
    done
  done
}

export -f ztosec
export -f zcapture

for f in logs/*; do
  id=$(basename $f | rev | cut -c 5- | rev)
  if [ -d "data/dynamite/$id" ]; then
    echo "$id already done"
    continue
  else
    echo "now $id"
  fi
  # [00:01:49.68]  Croatia (`WK-Tade-FB`) fires Dynamite
  ts=$(grep -a 'fires Dynamite' < $f | cut -c 2-12 | xargs -I% bash -c 'ztosec %')
  echo "$ts" | xargs -L1 -I% bash -c 'zcapture %' $id
  echo "game $id done -- next log"
done

